[package]
name = "binage"
version = "0.1.0"
authors = ["dhasane <danihas@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = "0.23.12"
clap = { version = "3.1.8", features = ["derive"] }
